### ISSUE TITLE
Postgres container to interface with foreign databases

### ISSUE THREAD

**Issue by chbrandt** [chbrandt/docker-dachs#5]
Imagine there are different postgres servers providing data; let's say each one is dedicated to different wavebands -- say one for optical and another one for infrared photometric tables. Consider these two databases were generated by DaCHS (at some point of Universe history) and as such they/we have the respective RDs (this is probably not necessary, but it simplifies the dependencies scenario).

It would be nice to be able to connect DaCHS to both of the database/servers. With such feature, it would be possible to move or spread data among different servers -- or containers -- efficiently.

What I have in mind, also, is that this should -- hopefully, _could_ -- be done in such manner as to not disturb DaCHS, the server, too much. In other words, it would be nice to push this burden to Postgres itself: a master (postgres) server talks to Dachs, and this _master_ -- linke an umbrella server -- is the one communicating with the actual database servers (e.g, optical and infrared databases).

I've done a search to see if/what could be done about it, and it seems as of Postgres 9.3 there is a module for such job: [postgres_fdw](https://www.postgresql.org/docs/9.3/static/postgres-fdw.html). "[dblink](https://www.postgresql.org/docs/9.3/static/dblink.html)" is another reference I found, looks like an old(er) way of doing such.

Also, the "[foreign data wrappers](https://wiki.postgresql.org/wiki/Foreign_data_wrappers)" section of postgres' wiki can be useful.

[]

**Comment by msdemlei** [comment]
On Thu, Sep 01, 2016 at 02:50:04AM -0700, Carlos Brandt wrote:
> It would be nice to be able to connect DaCHS to both of the
> database/servers. With such feature, it would be possible to move
> or spread data among different servers -- or containers --
> efficiently.

The foreign data wrappers you mention could indeed do this, albeit at
the price of a probably noticeable overhead.  It is still what I'd
recommend if you have to have such a construct.

This is despite DaCHS' existing capability to define as many access
profiles as you want; it's just that you cannot, for each table,
define the profiles that should be used to access that table.

In principle, it would be easy to let you define that.  But of
course, there's always a plethora of little issues that make this
kind of thing tricky.  The most serious one is that it would make TAP
an unsupportable nightmare -- what should DaCHS do if people request
joins between tables sitting in different databases?  With FDWs, the
joins are at least performed by the same postgres logic that does
that otherwise.

But anyway, the idea of having an RD is that it should be easy to
simply re-import the data when you migrate.  So, I'd say when you're
"federating" different services just ``gavo imp`` the RDs you want to
move and be done with them.  Avoid any futzing with fdws or even
moving dumps unless there's a *very* compelling reason to dodge the
re-import.

The DB connection is the most fragile part of DaCHS (at least if
judged by the number of problems people run into).  Hence my
conviction that it's wise to avoid complicating things in that area
further by throwing more databases into the fray.

          -- Markus

**Comment by chbrandt** [comment]
Thanks for the feedback, Markus. I'll hold the discussion (added some tags) to not lost track, until I think better about it and -- if that becomes the case -- move it forward.
